title: Car travel blog
author: Bert
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will showcase my awesome roadtrip in 2019. 

theme: minima

# social links
twitter_username: bert # DO NOT include the @ character, or else the build will fail!
github_username:  bert # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
